"""Write and index Markdown runbooks for resolved incidents."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from ..agent.incident import Incident

_FILENAME_STAMP = "%Y%m%d-%H%M%S"
_STAMP_LEN = len(datetime.now().strftime(_FILENAME_STAMP))


def _slug(text: str) -> str:
    text = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s_-]+", "-", text).strip("-")[:60] or "incident"


def _section(text: str, *, placeholder: str = "_Not determined._") -> str:
    return text.strip() if text and text.strip() else placeholder


def _bullets(items: list[str], *, placeholder: str = "_None recorded._") -> str:
    return "\n".join(f"- {item}" for item in items) if items else placeholder


@dataclass(frozen=True)
class RunbookLibrary:
    """Manages a directory of runbook Markdown files plus an index."""

    directory: Path
    cluster: str = "unknown"
    backend: str = "unknown"

    def __post_init__(self) -> None:
        self.directory.mkdir(parents=True, exist_ok=True)

    def save(self, incident: Incident) -> Path:
        now = datetime.now(tz=timezone.utc)
        title = incident.title()
        path = self.directory / f"{now.strftime(_FILENAME_STAMP)}-{_slug(title)}.md"
        path.write_text(self._render(incident, title, now), encoding="utf-8")
        return path

    def _render(self, incident: Incident, title: str, now: datetime) -> str:
        status = "Resolved" if incident.resolved else "Investigating"
        return f"""# {title}

| | |
|---|---|
| **Generated** | {now.strftime('%Y-%m-%d %H:%M UTC')} |
| **Cluster** | {self.cluster} |
| **Backend** | {self.backend} |
| **Status** | {status} |

## Summary

{_section(incident.request)}

## Affected resources

{_bullets(incident.affected)}

## Root cause

{_section(incident.root_cause)}

## Fix applied

{_section(incident.remediation)}

## Verification

{_bullets(incident.verification)}

## Prevention

{_section(incident.prevention)}

<details>
<summary>Full diagnostic transcript</summary>

{incident.narrative or "_No transcript captured._"}

</details>

---

_Generated by KubeMedic._
"""

    def entries(self) -> list[Path]:
        return sorted(
            (p for p in self.directory.glob("*.md") if p.name != "index.md"),
            reverse=True,
        )

    def write_index(self) -> Path:
        rows = ["# Runbook index", "", f"Total: **{len(self.entries())}**", "", "| Date | Runbook |", "|------|---------|"]
        for path in self.entries():
            rows.append(f"| {self._date_label(path)} | [{self._title_label(path)}]({path.name}) |")
        index = self.directory / "index.md"
        index.write_text("\n".join(rows) + "\n", encoding="utf-8")
        return index

    @staticmethod
    def _date_label(path: Path) -> str:
        try:
            return datetime.strptime(path.stem[:_STAMP_LEN], _FILENAME_STAMP).strftime("%Y-%m-%d %H:%M")
        except ValueError:
            return "?"

    @staticmethod
    def _title_label(path: Path) -> str:
        remainder = path.stem[_STAMP_LEN + 1 :]
        return remainder.replace("-", " ").title() if remainder else path.stem
